const CONFIG_KEY='railwaynotes_supabase_config';
let supabase=null,currentUser=null,currentMonth=new Date(),selectedDate=null,noteCache=new Map(),reportType='daily';
const $=id=>document.getElementById(id);
function show(id){['authView','setupView','mainView','reportsView'].forEach(x=>$(x).classList.add('hidden'));$(id).classList.remove('hidden')}
function config(){try{return JSON.parse(localStorage.getItem(CONFIG_KEY)||'null')}catch{return null}}
function init(){const c=config();if(!c){show('setupView');return}supabase=window.supabase.createClient(c.url,c.key);bind();supabase.auth.onAuthStateChange((_,session)=>{currentUser=session?.user||null;if(currentUser){$('userEmail').textContent=currentUser.email||'';show('mainView');loadCalendar()}else show('authView')});supabase.auth.getSession().then(({data})=>{if(data.session){currentUser=data.session.user;show('mainView');$('userEmail').textContent=currentUser.email||'';loadCalendar()}else show('authView')})}
function bind(){ $('saveConfig').onclick=()=>{const url=$('sbUrl').value.trim(),key=$('sbKey').value.trim();if(!url||!key){$('setupMessage').textContent='Enter both values.';return}localStorage.setItem(CONFIG_KEY,JSON.stringify({url,key}));location.reload()};let signup=false;$('toggleAuth').onclick=()=>{signup=!signup;$('authButton').textContent=signup?'Create account':'Sign in';$('toggleAuth').textContent=signup?'Already have an account? Sign in':'Create an account'};$('authForm').onsubmit=async e=>{e.preventDefault();$('authMessage').textContent='';const email=$('email').value.trim(),password=$('password').value;const r=signup?await supabase.auth.signUp({email,password}):await supabase.auth.signInWithPassword({email,password});if(r.error)$('authMessage').textContent=r.error.message;else if(signup)$('authMessage').textContent='Account created. Check your email if confirmation is enabled.'};$('signOut').onclick=()=>supabase.auth.signOut();$('prevMonth').onclick=()=>{currentMonth=new Date(currentMonth.getFullYear(),currentMonth.getMonth()-1,1);loadCalendar()};$('nextMonth').onclick=()=>{currentMonth=new Date(currentMonth.getFullYear(),currentMonth.getMonth()+1,1);loadCalendar()};$('todayBtn').onclick=()=>{currentMonth=new Date();selectedDate=isoDate(new Date());loadCalendar();loadNote()};$('saveNote').onclick=saveNote;$('deleteNote').onclick=deleteNote;$('reportsBtn').onclick=()=>{show('reportsView');setReportDates()};$('backBtn').onclick=()=>{show('mainView');loadCalendar()};document.querySelectorAll('[data-type]').forEach(b=>b.onclick=()=>{document.querySelectorAll('[data-type]').forEach(x=>x.classList.remove('active'));b.classList.add('active');reportType=b.dataset.type;setReportDates()});$('generateReport').onclick=generateReport}
function isoDate(d){return new Date(d.getTime()-d.getTimezoneOffset()*60000).toISOString().slice(0,10)}
function esc(s){return String(s).replace(/[&<>\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\\':'&#92;','"':'&quot;'}[c]))}
async function loadCalendar(){if(!currentUser)return;const y=currentMonth.getFullYear(),m=currentMonth.getMonth();$('monthTitle').textContent=new Intl.DateTimeFormat(undefined,{month:'long',year:'numeric'}).format(currentMonth);const first=new Date(y,m,1),start=new Date(y,m,1-first.getDay()),end=new Date(y,m+1,0);const q=await supabase.from('daily_notes').select('note_date').eq('user_id',currentUser.id).gte('note_date',isoDate(start)).lte('note_date',isoDate(end));if(q.error){noteCache=new Map()}else{noteCache=new Map(q.data.map(x=>[x.note_date,true]))}const today=isoDate(new Date());let html='';for(let i=0;i<42;i++){const d=new Date(start);d.setDate(start.getDate()+i);const ds=isoDate(d),cls=['day',d.getMonth()!==m?'other':'',ds===today?'today':'',ds===selectedDate?'selected':'',noteCache.has(ds)?'has-note':''].filter(Boolean).join(' ');html+=`<button class="${cls}" data-date="${ds}">${d.getDate()}</button>`}$('calendar').innerHTML=html;document.querySelectorAll('.day').forEach(b=>b.onclick=()=>{selectedDate=b.dataset.date;loadCalendar();loadNote()});if(selectedDate)loadNote()}
async function loadNote(){if(!selectedDate||!currentUser)return;$('selectedDate').textContent=new Intl.DateTimeFormat(undefined,{dateStyle:'full'}).format(new Date(selectedDate+'T00:00:00'));$('noteText').disabled=false;$('saveNote').disabled=false;$('deleteNote').disabled=false;$('noteStatus').textContent='Loading…';const {data,error}=await supabase.from('daily_notes').select('note').eq('user_id',currentUser.id).eq('note_date',selectedDate).maybeSingle();$('noteText').value=error?'':(data?.note||'');$('noteStatus').textContent=error?'Unable to load note.':'Your private daily note';}
async function saveNote(){const note=$('noteText').value;const {error}=await supabase.from('daily_notes').upsert({user_id:currentUser.id,note_date:selectedDate,note,updated_at:new Date().toISOString()},{onConflict:'user_id,note_date'});if(error){$('noteStatus').textContent=error.message;return}$('noteStatus').textContent='Saved just now';loadCalendar()}
async function deleteNote(){if(!selectedDate||!confirm('Delete this note?'))return;const {error}=await supabase.from('daily_notes').delete().eq('user_id',currentUser.id).eq('note_date',selectedDate);if(error){$('noteStatus').textContent=error.message;return}$('noteText').value='';$('noteStatus').textContent='Deleted';loadCalendar()}
function setReportDates(){const d=new Date();let from,to;if(reportType==='daily'){from=to=isoDate(d)}else if(reportType==='weekly'){const day=d.getDay();const s=new Date(d);s.setDate(d.getDate()-day);const e=new Date(s);e.setDate(s.getDate()+6);from=isoDate(s);to=isoDate(e)}else if(reportType==='monthly'){from=isoDate(new Date(d.getFullYear(),d.getMonth(),1));to=isoDate(new Date(d.getFullYear(),d.getMonth()+1,0))}else{from=$('reportFrom').value||isoDate(d);to=$('reportTo').value||isoDate(d)}$('reportFrom').value=from;$('reportTo').value=to}
async function generateReport(){const from=$('reportFrom').value,to=$('reportTo').value;if(!from||!to||from>to)return;const {data,error}=await supabase.from('daily_notes').select('note_date,note').eq('user_id',currentUser.id).gte('note_date',from).lte('note_date',to).order('note_date');if(error){$('reportOutput').innerHTML=`<p class="message">${esc(error.message)}</p>`;return}const title=reportType[0].toUpperCase()+reportType.slice(1)+' Report';let html=`<div class="report-title"><div><h2>${title}</h2><p class="muted">${from} to ${to}</p></div><button class="export" onclick="exportPdf()">Export PDF</button></div>`;html+=data?.length?data.map(x=>`<div class="report-entry"><strong>${new Intl.DateTimeFormat(undefined,{dateStyle:'full'}).format(new Date(x.note_date+'T00:00:00'))}</strong><br>${esc(x.note||'')}</div>`).join(''):'<p class="muted">No notes found for this period.</p>';$('reportOutput').innerHTML=html}
async function exportPdf(){const {jsPDF}=window.jspdf;const doc=new jsPDF();const from=$('reportFrom').value,to=$('reportTo').value;const {data}=await supabase.from('daily_notes').select('note_date,note').eq('user_id',currentUser.id).gte('note_date',from).lte('note_date',to).order('note_date');let y=18;doc.setFontSize(18);doc.text('Railway Notes Report',14,y);y+=9;doc.setFontSize(11);doc.text(`${from} to ${to}`,14,y);y+=10;for(const x of (data||[])){const head=x.note_date;const lines=doc.splitTextToSize(x.note||'',180);if(y+12+lines.length*5>285){doc.addPage();y=18}doc.setFont(undefined,'bold');doc.text(head,14,y);y+=6;doc.setFont(undefined,'normal');doc.text(lines,14,y);y+=lines.length*5+7}doc.save(`railway-notes-${from}-to-${to}.pdf`)}
window.exportPdf=exportPdf;init();
