-- Run this once in Supabase SQL Editor.
create table if not exists public.daily_notes (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  note_date date not null,
  note text not null default '',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(user_id, note_date)
);

alter table public.daily_notes enable row level security;

drop policy if exists "Users can view own notes" on public.daily_notes;
drop policy if exists "Users can insert own notes" on public.daily_notes;
drop policy if exists "Users can update own notes" on public.daily_notes;
drop policy if exists "Users can delete own notes" on public.daily_notes;

create policy "Users can view own notes" on public.daily_notes for select using (auth.uid() = user_id);
create policy "Users can insert own notes" on public.daily_notes for insert with check (auth.uid() = user_id);
create policy "Users can update own notes" on public.daily_notes for update using (auth.uid() = user_id) with check (auth.uid() = user_id);
create policy "Users can delete own notes" on public.daily_notes for delete using (auth.uid() = user_id);

create index if not exists daily_notes_user_date_idx on public.daily_notes(user_id, note_date);
